// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectInfos.proto

#ifndef PROTOBUF_INCLUDED_objectInfos_2eproto
#define PROTOBUF_INCLUDED_objectInfos_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_objectInfos_2eproto 

namespace protobuf_objectInfos_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_objectInfos_2eproto
namespace proto {
class objectInfos;
class objectInfosDefaultTypeInternal;
extern objectInfosDefaultTypeInternal _objectInfos_default_instance_;
class objectInfos_objectInfo;
class objectInfos_objectInfoDefaultTypeInternal;
extern objectInfos_objectInfoDefaultTypeInternal _objectInfos_objectInfo_default_instance_;
}  // namespace proto
namespace google {
namespace protobuf {
template<> ::proto::objectInfos* Arena::CreateMaybeMessage<::proto::objectInfos>(Arena*);
template<> ::proto::objectInfos_objectInfo* Arena::CreateMaybeMessage<::proto::objectInfos_objectInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace proto {

// ===================================================================

class objectInfos_objectInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.objectInfos.objectInfo) */ {
 public:
  objectInfos_objectInfo();
  virtual ~objectInfos_objectInfo();

  objectInfos_objectInfo(const objectInfos_objectInfo& from);

  inline objectInfos_objectInfo& operator=(const objectInfos_objectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  objectInfos_objectInfo(objectInfos_objectInfo&& from) noexcept
    : objectInfos_objectInfo() {
    *this = ::std::move(from);
  }

  inline objectInfos_objectInfo& operator=(objectInfos_objectInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const objectInfos_objectInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const objectInfos_objectInfo* internal_default_instance() {
    return reinterpret_cast<const objectInfos_objectInfo*>(
               &_objectInfos_objectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(objectInfos_objectInfo* other);
  friend void swap(objectInfos_objectInfo& a, objectInfos_objectInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline objectInfos_objectInfo* New() const final {
    return CreateMaybeMessage<objectInfos_objectInfo>(NULL);
  }

  objectInfos_objectInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<objectInfos_objectInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const objectInfos_objectInfo& from);
  void MergeFrom(const objectInfos_objectInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(objectInfos_objectInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 objClass = 1;
  bool has_objclass() const;
  void clear_objclass();
  static const int kObjClassFieldNumber = 1;
  ::google::protobuf::int32 objclass() const;
  void set_objclass(::google::protobuf::int32 value);

  // optional float score = 2;
  bool has_score() const;
  void clear_score();
  static const int kScoreFieldNumber = 2;
  float score() const;
  void set_score(float value);

  // optional int32 tlx = 3;
  bool has_tlx() const;
  void clear_tlx();
  static const int kTlxFieldNumber = 3;
  ::google::protobuf::int32 tlx() const;
  void set_tlx(::google::protobuf::int32 value);

  // optional int32 tly = 4;
  bool has_tly() const;
  void clear_tly();
  static const int kTlyFieldNumber = 4;
  ::google::protobuf::int32 tly() const;
  void set_tly(::google::protobuf::int32 value);

  // optional int32 brx = 5;
  bool has_brx() const;
  void clear_brx();
  static const int kBrxFieldNumber = 5;
  ::google::protobuf::int32 brx() const;
  void set_brx(::google::protobuf::int32 value);

  // optional int32 bry = 6;
  bool has_bry() const;
  void clear_bry();
  static const int kBryFieldNumber = 6;
  ::google::protobuf::int32 bry() const;
  void set_bry(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto.objectInfos.objectInfo)
 private:
  void set_has_objclass();
  void clear_has_objclass();
  void set_has_score();
  void clear_has_score();
  void set_has_tlx();
  void clear_has_tlx();
  void set_has_tly();
  void clear_has_tly();
  void set_has_brx();
  void clear_has_brx();
  void set_has_bry();
  void clear_has_bry();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 objclass_;
  float score_;
  ::google::protobuf::int32 tlx_;
  ::google::protobuf::int32 tly_;
  ::google::protobuf::int32 brx_;
  ::google::protobuf::int32 bry_;
  friend struct ::protobuf_objectInfos_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class objectInfos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.objectInfos) */ {
 public:
  objectInfos();
  virtual ~objectInfos();

  objectInfos(const objectInfos& from);

  inline objectInfos& operator=(const objectInfos& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  objectInfos(objectInfos&& from) noexcept
    : objectInfos() {
    *this = ::std::move(from);
  }

  inline objectInfos& operator=(objectInfos&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const objectInfos& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const objectInfos* internal_default_instance() {
    return reinterpret_cast<const objectInfos*>(
               &_objectInfos_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(objectInfos* other);
  friend void swap(objectInfos& a, objectInfos& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline objectInfos* New() const final {
    return CreateMaybeMessage<objectInfos>(NULL);
  }

  objectInfos* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<objectInfos>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const objectInfos& from);
  void MergeFrom(const objectInfos& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(objectInfos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef objectInfos_objectInfo objectInfo;

  // accessors -------------------------------------------------------

  // repeated .proto.objectInfos.objectInfo infos = 1;
  int infos_size() const;
  void clear_infos();
  static const int kInfosFieldNumber = 1;
  ::proto::objectInfos_objectInfo* mutable_infos(int index);
  ::google::protobuf::RepeatedPtrField< ::proto::objectInfos_objectInfo >*
      mutable_infos();
  const ::proto::objectInfos_objectInfo& infos(int index) const;
  ::proto::objectInfos_objectInfo* add_infos();
  const ::google::protobuf::RepeatedPtrField< ::proto::objectInfos_objectInfo >&
      infos() const;

  // @@protoc_insertion_point(class_scope:proto.objectInfos)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::proto::objectInfos_objectInfo > infos_;
  friend struct ::protobuf_objectInfos_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// objectInfos_objectInfo

// optional int32 objClass = 1;
inline bool objectInfos_objectInfo::has_objclass() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void objectInfos_objectInfo::set_has_objclass() {
  _has_bits_[0] |= 0x00000001u;
}
inline void objectInfos_objectInfo::clear_has_objclass() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void objectInfos_objectInfo::clear_objclass() {
  objclass_ = 0;
  clear_has_objclass();
}
inline ::google::protobuf::int32 objectInfos_objectInfo::objclass() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.objClass)
  return objclass_;
}
inline void objectInfos_objectInfo::set_objclass(::google::protobuf::int32 value) {
  set_has_objclass();
  objclass_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.objClass)
}

// optional float score = 2;
inline bool objectInfos_objectInfo::has_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void objectInfos_objectInfo::set_has_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void objectInfos_objectInfo::clear_has_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void objectInfos_objectInfo::clear_score() {
  score_ = 0;
  clear_has_score();
}
inline float objectInfos_objectInfo::score() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.score)
  return score_;
}
inline void objectInfos_objectInfo::set_score(float value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.score)
}

// optional int32 tlx = 3;
inline bool objectInfos_objectInfo::has_tlx() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void objectInfos_objectInfo::set_has_tlx() {
  _has_bits_[0] |= 0x00000004u;
}
inline void objectInfos_objectInfo::clear_has_tlx() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void objectInfos_objectInfo::clear_tlx() {
  tlx_ = 0;
  clear_has_tlx();
}
inline ::google::protobuf::int32 objectInfos_objectInfo::tlx() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.tlx)
  return tlx_;
}
inline void objectInfos_objectInfo::set_tlx(::google::protobuf::int32 value) {
  set_has_tlx();
  tlx_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.tlx)
}

// optional int32 tly = 4;
inline bool objectInfos_objectInfo::has_tly() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void objectInfos_objectInfo::set_has_tly() {
  _has_bits_[0] |= 0x00000008u;
}
inline void objectInfos_objectInfo::clear_has_tly() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void objectInfos_objectInfo::clear_tly() {
  tly_ = 0;
  clear_has_tly();
}
inline ::google::protobuf::int32 objectInfos_objectInfo::tly() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.tly)
  return tly_;
}
inline void objectInfos_objectInfo::set_tly(::google::protobuf::int32 value) {
  set_has_tly();
  tly_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.tly)
}

// optional int32 brx = 5;
inline bool objectInfos_objectInfo::has_brx() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void objectInfos_objectInfo::set_has_brx() {
  _has_bits_[0] |= 0x00000010u;
}
inline void objectInfos_objectInfo::clear_has_brx() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void objectInfos_objectInfo::clear_brx() {
  brx_ = 0;
  clear_has_brx();
}
inline ::google::protobuf::int32 objectInfos_objectInfo::brx() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.brx)
  return brx_;
}
inline void objectInfos_objectInfo::set_brx(::google::protobuf::int32 value) {
  set_has_brx();
  brx_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.brx)
}

// optional int32 bry = 6;
inline bool objectInfos_objectInfo::has_bry() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void objectInfos_objectInfo::set_has_bry() {
  _has_bits_[0] |= 0x00000020u;
}
inline void objectInfos_objectInfo::clear_has_bry() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void objectInfos_objectInfo::clear_bry() {
  bry_ = 0;
  clear_has_bry();
}
inline ::google::protobuf::int32 objectInfos_objectInfo::bry() const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.objectInfo.bry)
  return bry_;
}
inline void objectInfos_objectInfo::set_bry(::google::protobuf::int32 value) {
  set_has_bry();
  bry_ = value;
  // @@protoc_insertion_point(field_set:proto.objectInfos.objectInfo.bry)
}

// -------------------------------------------------------------------

// objectInfos

// repeated .proto.objectInfos.objectInfo infos = 1;
inline int objectInfos::infos_size() const {
  return infos_.size();
}
inline void objectInfos::clear_infos() {
  infos_.Clear();
}
inline ::proto::objectInfos_objectInfo* objectInfos::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:proto.objectInfos.infos)
  return infos_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::proto::objectInfos_objectInfo >*
objectInfos::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:proto.objectInfos.infos)
  return &infos_;
}
inline const ::proto::objectInfos_objectInfo& objectInfos::infos(int index) const {
  // @@protoc_insertion_point(field_get:proto.objectInfos.infos)
  return infos_.Get(index);
}
inline ::proto::objectInfos_objectInfo* objectInfos::add_infos() {
  // @@protoc_insertion_point(field_add:proto.objectInfos.infos)
  return infos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::proto::objectInfos_objectInfo >&
objectInfos::infos() const {
  // @@protoc_insertion_point(field_list:proto.objectInfos.infos)
  return infos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_objectInfos_2eproto
