// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objectInfos.proto

#include "objectInfos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_objectInfos_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_objectInfos_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_objectInfos_objectInfo;
}  // namespace protobuf_objectInfos_2eproto
namespace proto {
class objectInfos_objectInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<objectInfos_objectInfo>
      _instance;
} _objectInfos_objectInfo_default_instance_;
class objectInfosDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<objectInfos>
      _instance;
} _objectInfos_default_instance_;
}  // namespace proto
namespace protobuf_objectInfos_2eproto {
static void InitDefaultsobjectInfos_objectInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_objectInfos_objectInfo_default_instance_;
    new (ptr) ::proto::objectInfos_objectInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::objectInfos_objectInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_objectInfos_objectInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsobjectInfos_objectInfo}, {}};

static void InitDefaultsobjectInfos() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_objectInfos_default_instance_;
    new (ptr) ::proto::objectInfos();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::objectInfos::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_objectInfos =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsobjectInfos}, {
      &protobuf_objectInfos_2eproto::scc_info_objectInfos_objectInfo.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_objectInfos_objectInfo.base);
  ::google::protobuf::internal::InitSCC(&scc_info_objectInfos.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, objclass_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, tlx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, tly_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, brx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos_objectInfo, bry_),
  0,
  1,
  2,
  3,
  4,
  5,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::objectInfos, infos_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::proto::objectInfos_objectInfo)},
  { 17, 23, sizeof(::proto::objectInfos)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_objectInfos_objectInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_objectInfos_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "objectInfos.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021objectInfos.proto\022\005proto\"\236\001\n\013objectInf"
      "os\022,\n\005infos\030\001 \003(\0132\035.proto.objectInfos.ob"
      "jectInfo\032a\n\nobjectInfo\022\020\n\010objClass\030\001 \001(\005"
      "\022\r\n\005score\030\002 \001(\002\022\013\n\003tlx\030\003 \001(\005\022\013\n\003tly\030\004 \001("
      "\005\022\013\n\003brx\030\005 \001(\005\022\013\n\003bry\030\006 \001(\005"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objectInfos.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_objectInfos_2eproto
namespace proto {

// ===================================================================

void objectInfos_objectInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int objectInfos_objectInfo::kObjClassFieldNumber;
const int objectInfos_objectInfo::kScoreFieldNumber;
const int objectInfos_objectInfo::kTlxFieldNumber;
const int objectInfos_objectInfo::kTlyFieldNumber;
const int objectInfos_objectInfo::kBrxFieldNumber;
const int objectInfos_objectInfo::kBryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

objectInfos_objectInfo::objectInfos_objectInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_objectInfos_2eproto::scc_info_objectInfos_objectInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.objectInfos.objectInfo)
}
objectInfos_objectInfo::objectInfos_objectInfo(const objectInfos_objectInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&objclass_, &from.objclass_,
    static_cast<size_t>(reinterpret_cast<char*>(&bry_) -
    reinterpret_cast<char*>(&objclass_)) + sizeof(bry_));
  // @@protoc_insertion_point(copy_constructor:proto.objectInfos.objectInfo)
}

void objectInfos_objectInfo::SharedCtor() {
  ::memset(&objclass_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bry_) -
      reinterpret_cast<char*>(&objclass_)) + sizeof(bry_));
}

objectInfos_objectInfo::~objectInfos_objectInfo() {
  // @@protoc_insertion_point(destructor:proto.objectInfos.objectInfo)
  SharedDtor();
}

void objectInfos_objectInfo::SharedDtor() {
}

void objectInfos_objectInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* objectInfos_objectInfo::descriptor() {
  ::protobuf_objectInfos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectInfos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const objectInfos_objectInfo& objectInfos_objectInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_objectInfos_2eproto::scc_info_objectInfos_objectInfo.base);
  return *internal_default_instance();
}


void objectInfos_objectInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.objectInfos.objectInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    ::memset(&objclass_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&bry_) -
        reinterpret_cast<char*>(&objclass_)) + sizeof(bry_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool objectInfos_objectInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.objectInfos.objectInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 objClass = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_objclass();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &objclass_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float score = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          set_has_score();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 tlx = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_tlx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tlx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 tly = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_tly();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tly_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 brx = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_brx();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &brx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 bry = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_bry();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bry_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.objectInfos.objectInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.objectInfos.objectInfo)
  return false;
#undef DO_
}

void objectInfos_objectInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.objectInfos.objectInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 objClass = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->objclass(), output);
  }

  // optional float score = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->score(), output);
  }

  // optional int32 tlx = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->tlx(), output);
  }

  // optional int32 tly = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->tly(), output);
  }

  // optional int32 brx = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->brx(), output);
  }

  // optional int32 bry = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->bry(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.objectInfos.objectInfo)
}

::google::protobuf::uint8* objectInfos_objectInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.objectInfos.objectInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 objClass = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->objclass(), target);
  }

  // optional float score = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->score(), target);
  }

  // optional int32 tlx = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->tlx(), target);
  }

  // optional int32 tly = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->tly(), target);
  }

  // optional int32 brx = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->brx(), target);
  }

  // optional int32 bry = 6;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->bry(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.objectInfos.objectInfo)
  return target;
}

size_t objectInfos_objectInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.objectInfos.objectInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 63u) {
    // optional int32 objClass = 1;
    if (has_objclass()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->objclass());
    }

    // optional float score = 2;
    if (has_score()) {
      total_size += 1 + 4;
    }

    // optional int32 tlx = 3;
    if (has_tlx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->tlx());
    }

    // optional int32 tly = 4;
    if (has_tly()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->tly());
    }

    // optional int32 brx = 5;
    if (has_brx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->brx());
    }

    // optional int32 bry = 6;
    if (has_bry()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->bry());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void objectInfos_objectInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.objectInfos.objectInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const objectInfos_objectInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const objectInfos_objectInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.objectInfos.objectInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.objectInfos.objectInfo)
    MergeFrom(*source);
  }
}

void objectInfos_objectInfo::MergeFrom(const objectInfos_objectInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.objectInfos.objectInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      objclass_ = from.objclass_;
    }
    if (cached_has_bits & 0x00000002u) {
      score_ = from.score_;
    }
    if (cached_has_bits & 0x00000004u) {
      tlx_ = from.tlx_;
    }
    if (cached_has_bits & 0x00000008u) {
      tly_ = from.tly_;
    }
    if (cached_has_bits & 0x00000010u) {
      brx_ = from.brx_;
    }
    if (cached_has_bits & 0x00000020u) {
      bry_ = from.bry_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void objectInfos_objectInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.objectInfos.objectInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void objectInfos_objectInfo::CopyFrom(const objectInfos_objectInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.objectInfos.objectInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool objectInfos_objectInfo::IsInitialized() const {
  return true;
}

void objectInfos_objectInfo::Swap(objectInfos_objectInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void objectInfos_objectInfo::InternalSwap(objectInfos_objectInfo* other) {
  using std::swap;
  swap(objclass_, other->objclass_);
  swap(score_, other->score_);
  swap(tlx_, other->tlx_);
  swap(tly_, other->tly_);
  swap(brx_, other->brx_);
  swap(bry_, other->bry_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata objectInfos_objectInfo::GetMetadata() const {
  protobuf_objectInfos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectInfos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void objectInfos::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int objectInfos::kInfosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

objectInfos::objectInfos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_objectInfos_2eproto::scc_info_objectInfos.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.objectInfos)
}
objectInfos::objectInfos(const objectInfos& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      infos_(from.infos_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:proto.objectInfos)
}

void objectInfos::SharedCtor() {
}

objectInfos::~objectInfos() {
  // @@protoc_insertion_point(destructor:proto.objectInfos)
  SharedDtor();
}

void objectInfos::SharedDtor() {
}

void objectInfos::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* objectInfos::descriptor() {
  ::protobuf_objectInfos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectInfos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const objectInfos& objectInfos::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_objectInfos_2eproto::scc_info_objectInfos.base);
  return *internal_default_instance();
}


void objectInfos::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.objectInfos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  infos_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool objectInfos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.objectInfos)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .proto.objectInfos.objectInfo infos = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_infos()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.objectInfos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.objectInfos)
  return false;
#undef DO_
}

void objectInfos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.objectInfos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .proto.objectInfos.objectInfo infos = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->infos_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->infos(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.objectInfos)
}

::google::protobuf::uint8* objectInfos::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.objectInfos)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .proto.objectInfos.objectInfo infos = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->infos_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->infos(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.objectInfos)
  return target;
}

size_t objectInfos::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.objectInfos)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .proto.objectInfos.objectInfo infos = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->infos_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->infos(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void objectInfos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.objectInfos)
  GOOGLE_DCHECK_NE(&from, this);
  const objectInfos* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const objectInfos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.objectInfos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.objectInfos)
    MergeFrom(*source);
  }
}

void objectInfos::MergeFrom(const objectInfos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.objectInfos)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  infos_.MergeFrom(from.infos_);
}

void objectInfos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.objectInfos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void objectInfos::CopyFrom(const objectInfos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.objectInfos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool objectInfos::IsInitialized() const {
  return true;
}

void objectInfos::Swap(objectInfos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void objectInfos::InternalSwap(objectInfos* other) {
  using std::swap;
  CastToBase(&infos_)->InternalSwap(CastToBase(&other->infos_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata objectInfos::GetMetadata() const {
  protobuf_objectInfos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_objectInfos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::objectInfos_objectInfo* Arena::CreateMaybeMessage< ::proto::objectInfos_objectInfo >(Arena* arena) {
  return Arena::CreateInternal< ::proto::objectInfos_objectInfo >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::objectInfos* Arena::CreateMaybeMessage< ::proto::objectInfos >(Arena* arena) {
  return Arena::CreateInternal< ::proto::objectInfos >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
